### ISSUE TITLE
Use Python version 3.6 to 3.8 for Isaac Gym compatibility.

### ISSUE THREAD

**Issue by minoring** [clvrai/furniture-bench#10]

**Comment by ankile** [comment]
FYI and FWIW, I only got everything working with `python==3.8` exactly, as some parts required `python>=3.8` and others `python<=3.8` :)

**Comment by minoring** [comment]
Thanks for pointing that out! Indeed, that is a valid point.  I encountered dependency conflicts while trying to install Python 3.7. The subsequent commits will clarify the requirements of Python 3.8 :
- https://github.com/clvrai/furniture-bench/commit/c243ae66d020e9adaea6e017f5f2d931fd9ba266
- https://github.com/clvrai/furniture-bench/commit/3a226996b53cc654d322a10cd07d3f2a1c0b4336
