### ISSUE TITLE
Visualizing environment on remote machine

### ISSUE THREAD

**Issue by ankile** [clvrai/furniture-bench#15]
Is there any recommended way of visualizing the environment and interactions on a remote machine? For example, would https://github.com/NVlabs/sim-web-visualizer/tree/main be a good solution, or do you have other preferred ways of going about this?

Let me know if the question is ill-posed; thank you!

**Comment by minoring** [comment]
We haven't attempted real-time visualization on the remote machine. Instead, we save trajectories as mp4 videos for later viewing. To save a trajectory, you can set the record flag to True (https://clvrai.github.io/furniture-bench/docs/tutorials/furniture_sim.html#furnituresim-configuration). For example, running this command `python -m furniture_bench.scripts.run_sim_env --furniture one_leg --scripted --record --headless` will save in-hand and front-view videos in the default directory (sim_record/).

Alternatively, you can visualize saved data from teleop or scripted agents using show_trajectory.py like this: `python -m furniture_bench.scripts.show_trajectory --data-path /home/minho/furniture-bench/scripted_sim_demo/one_leg/<name_of_pkl>` (reference: https://clvrai.github.io/furniture-bench/docs/tutorials/furniture_bench.html#visualize-robot-trajectory)

If you have any questions, feel free to ask!

**Comment by ankile** [comment]
Okay, that makes sense—thanks!

Saving recorded trajectories works well for now, and we'll let you know if we get the rig set up with `sim-web-visualizer` or something similar later. I am, however, not getting the recording to work. I've followed the installation instructions faithfully, I think, but all saved videos seem to be corrupt as my mp4 player refuses to open them. Is this the intended behavior, and does one have to use `show_trajectory` for the showing of the videos to work?
